version: "3"

services:
    postgres:
        container_name: postges_test
        image: postgres:14.4-alpine
        ports:
            -   "1337:5432"
        environment:
            POSTGRES_USER: "test"
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: "testDB"